#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun  8 13:53:16 2017

Testing Portsmouth

@author: arsalanadil
"""
import numpy as np, scipy.integrate as integrate, scipy as sp
import RemoteQuad as remote, matplotlib.pyplot as plt

"""
n=1000#first plot z=0.1 to z=100
clusterList = np.zeros((n,3))
for z in range(0,n):
    clusterList[z] = np.array([z/10,0,0])
    
c2 = np.zeros(n)
for i in range(0,n):
    c2[i] = remote.wignerRotation(clusterList[i,:],clusterList[i,:])[0][0][0]#this is wignerRotation from VarMatrix_Generalized.py

print("This window plots C2(z) vs Z")
plt.figure(5)
plt.semilogx(np.arange(0,n/10,0.1), c2,'r')
"""
    
n=100#now plot z = 0.001 to z=0.1
clusterList2 = np.zeros((n,3))
for z in range(0,n):
    clusterList2[z] = np.array([z/1000,0,0])
    
c22 = np.zeros(n)
for i in range(0,n):
    c22[i] = remote.wignerRotation(clusterList2[i,:],clusterList2[i,:])[0][0][0]#this is wignerRotation from VarMatrix_Generalized.py

print("This window plots C2(z) vs Z")
plt.figure(5)
plt.semilogx(np.arange(0,n/1000,0.001), c22,'r')

